/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/models/mm1/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate
         * @description Métricas analíticas (regime estacionário). Exige λ < μ.
         */
        post: operations["calculate_api_models_mm1_calculate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/mm1/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate
         * @description Simulação de eventos discretos com várias replicações independentes.
         */
        post: operations["simulate_api_models_mm1_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/mm1/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare
         * @description Compara o modelo analítico com a simulação, métrica a métrica.
         *
         *     Para cada métrica devolve o erro absoluto, o erro relativo (%) e se o valor
         *     analítico cai dentro do intervalo de confiança da simulação.
         */
        post: operations["compare_api_models_mm1_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/mmc/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate
         * @description Métricas analíticas (regime estacionário).
         */
        post: operations["calculate_api_models_mmc_calculate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/mmc/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate
         * @description Simulação de eventos discretos com várias replicações independentes.
         */
        post: operations["simulate_api_models_mmc_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/mmc/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare
         * @description Compara o analítico com a simulação, métrica a métrica.
         */
        post: operations["compare_api_models_mmc_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/mm1k/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate
         * @description Métricas analíticas (regime estacionário).
         */
        post: operations["calculate_api_models_mm1k_calculate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/mm1k/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate
         * @description Simulação de eventos discretos com várias replicações independentes.
         */
        post: operations["simulate_api_models_mm1k_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/mm1k/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare
         * @description Compara o analítico com a simulação, métrica a métrica.
         */
        post: operations["compare_api_models_mm1k_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/mmck/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate
         * @description Métricas analíticas (regime estacionário).
         */
        post: operations["calculate_api_models_mmck_calculate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/mmck/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate
         * @description Simulação de eventos discretos com várias replicações independentes.
         */
        post: operations["simulate_api_models_mmck_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/mmck/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare
         * @description Compara o analítico com a simulação, métrica a métrica.
         */
        post: operations["compare_api_models_mmck_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Verifica se a API está no ar.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ComparisonResponse */
        ComparisonResponse: {
            /**
             * Model
             * @default M/M/1
             */
            model: string;
            /** Lambda */
            lambda: number;
            /** Mu */
            mu: number;
            /** Simulation Time */
            simulation_time: number;
            /** Warmup Time */
            warmup_time: number;
            /** Replications */
            replications: number;
            /** Seed */
            seed: number;
            /** Confidence Level */
            confidence_level: number;
            /** Metrics */
            metrics: {
                [key: string]: components["schemas"]["MetricComparisonOut"];
            };
            /** All Within Ci */
            all_within_ci: boolean | null;
            /** Max Relative Error Pct */
            max_relative_error_pct: number | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Fields */
            fields?: components["schemas"]["FieldError"][] | null;
        };
        /** FieldError */
        FieldError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /**
         * MM1CalculateRequest
         * @example {
         *       "lambda": 40,
         *       "mu": 50
         *     }
         */
        MM1CalculateRequest: {
            /**
             * Lambda
             * @description Taxa média de chegada (λ).
             */
            lambda: number;
            /**
             * Mu
             * @description Taxa média de serviço (μ).
             */
            mu: number;
        };
        /** MM1CalculateResponse */
        MM1CalculateResponse: {
            /**
             * Model
             * @default M/M/1
             */
            model: string;
            /** Rho */
            rho: number;
            /** L */
            L: number;
            /** Lq */
            Lq: number;
            /** W */
            W: number;
            /** Wq */
            Wq: number;
            /** P0 */
            p0: number;
        };
        /**
         * MM1CompareRequest
         * @description Mesmos parâmetros da simulação: o analítico usa apenas λ e μ.
         * @example {
         *       "lambda": 40,
         *       "mu": 50,
         *       "replications": 10,
         *       "seed": 2026,
         *       "simulation_time": 2000,
         *       "warmup_time": 100
         *     }
         */
        MM1CompareRequest: {
            /**
             * Lambda
             * @description Taxa média de chegada (λ).
             */
            lambda: number;
            /**
             * Mu
             * @description Taxa média de serviço (μ).
             */
            mu: number;
            /**
             * Simulation Time
             * @description Tempo simulado por replicação.
             */
            simulation_time: number;
            /**
             * Replications
             * @description Número de replicações.
             * @default 10
             */
            replications: number;
            /**
             * Warmup Time
             * @description Período inicial descartado (transitório).
             * @default 0
             */
            warmup_time: number;
            /**
             * Seed
             * @description Semente aleatória. Se omitida, uma é sorteada e devolvida.
             */
            seed?: number | null;
            /**
             * Confidence Level
             * @description Nível do intervalo de confiança (0 a 1).
             * @default 0.95
             */
            confidence_level: number;
        };
        /**
         * MM1KCalculateRequest
         * @example {
         *       "capacity": 5,
         *       "lambda": 12,
         *       "mu": 10
         *     }
         */
        MM1KCalculateRequest: {
            /**
             * Lambda
             * @description Taxa média de chegada (λ).
             */
            lambda: number;
            /**
             * Mu
             * @description Taxa média de serviço (μ).
             */
            mu: number;
            /**
             * Capacity
             * @description Capacidade total do sistema, em clientes (K).
             */
            capacity: number;
        };
        /**
         * MM1KSimulateRequest
         * @example {
         *       "capacity": 5,
         *       "lambda": 12,
         *       "mu": 10,
         *       "replications": 10,
         *       "seed": 2026,
         *       "simulation_time": 2000,
         *       "warmup_time": 100
         *     }
         */
        MM1KSimulateRequest: {
            /**
             * Lambda
             * @description Taxa média de chegada (λ).
             */
            lambda: number;
            /**
             * Mu
             * @description Taxa média de serviço (μ).
             */
            mu: number;
            /**
             * Simulation Time
             * @description Tempo simulado por replicação.
             */
            simulation_time: number;
            /**
             * Replications
             * @description Número de replicações.
             * @default 10
             */
            replications: number;
            /**
             * Warmup Time
             * @description Período inicial descartado (transitório).
             * @default 0
             */
            warmup_time: number;
            /**
             * Seed
             * @description Semente aleatória. Se omitida, uma é sorteada e devolvida.
             */
            seed?: number | null;
            /**
             * Confidence Level
             * @description Nível do intervalo de confiança (0 a 1).
             * @default 0.95
             */
            confidence_level: number;
            /**
             * Capacity
             * @description Capacidade total do sistema, em clientes (K).
             */
            capacity: number;
        };
        /**
         * MM1SimulateRequest
         * @example {
         *       "lambda": 40,
         *       "mu": 50,
         *       "replications": 10,
         *       "seed": 2026,
         *       "simulation_time": 2000,
         *       "warmup_time": 100
         *     }
         */
        MM1SimulateRequest: {
            /**
             * Lambda
             * @description Taxa média de chegada (λ).
             */
            lambda: number;
            /**
             * Mu
             * @description Taxa média de serviço (μ).
             */
            mu: number;
            /**
             * Simulation Time
             * @description Tempo simulado por replicação.
             */
            simulation_time: number;
            /**
             * Replications
             * @description Número de replicações.
             * @default 10
             */
            replications: number;
            /**
             * Warmup Time
             * @description Período inicial descartado (transitório).
             * @default 0
             */
            warmup_time: number;
            /**
             * Seed
             * @description Semente aleatória. Se omitida, uma é sorteada e devolvida.
             */
            seed?: number | null;
            /**
             * Confidence Level
             * @description Nível do intervalo de confiança (0 a 1).
             * @default 0.95
             */
            confidence_level: number;
        };
        /**
         * MMCCalculateRequest
         * @example {
         *       "lambda": 8,
         *       "mu": 1,
         *       "servers": 10
         *     }
         */
        MMCCalculateRequest: {
            /**
             * Lambda
             * @description Taxa média de chegada (λ).
             */
            lambda: number;
            /**
             * Mu
             * @description Taxa média de serviço (μ).
             */
            mu: number;
            /**
             * Servers
             * @description Número de servidores (c).
             */
            servers: number;
        };
        /**
         * MMCKCalculateRequest
         * @example {
         *       "capacity": 6,
         *       "lambda": 25,
         *       "mu": 10,
         *       "servers": 3
         *     }
         */
        MMCKCalculateRequest: {
            /**
             * Lambda
             * @description Taxa média de chegada (λ).
             */
            lambda: number;
            /**
             * Mu
             * @description Taxa média de serviço (μ).
             */
            mu: number;
            /**
             * Servers
             * @description Número de servidores (c).
             */
            servers: number;
            /**
             * Capacity
             * @description Capacidade total do sistema (K), incluindo os clientes em atendimento. Deve ser ≥ servers.
             */
            capacity: number;
        };
        /**
         * MMCKSimulateRequest
         * @example {
         *       "capacity": 6,
         *       "lambda": 25,
         *       "mu": 10,
         *       "replications": 10,
         *       "seed": 2026,
         *       "servers": 3,
         *       "simulation_time": 2000,
         *       "warmup_time": 100
         *     }
         */
        MMCKSimulateRequest: {
            /**
             * Lambda
             * @description Taxa média de chegada (λ).
             */
            lambda: number;
            /**
             * Mu
             * @description Taxa média de serviço (μ).
             */
            mu: number;
            /**
             * Simulation Time
             * @description Tempo simulado por replicação.
             */
            simulation_time: number;
            /**
             * Replications
             * @description Número de replicações.
             * @default 10
             */
            replications: number;
            /**
             * Warmup Time
             * @description Período inicial descartado (transitório).
             * @default 0
             */
            warmup_time: number;
            /**
             * Seed
             * @description Semente aleatória. Se omitida, uma é sorteada e devolvida.
             */
            seed?: number | null;
            /**
             * Confidence Level
             * @description Nível do intervalo de confiança (0 a 1).
             * @default 0.95
             */
            confidence_level: number;
            /**
             * Servers
             * @description Número de servidores (c).
             */
            servers: number;
            /**
             * Capacity
             * @description Capacidade total do sistema (K), incluindo os clientes em atendimento. Deve ser ≥ servers.
             */
            capacity: number;
        };
        /**
         * MMCSimulateRequest
         * @example {
         *       "lambda": 8,
         *       "mu": 1,
         *       "replications": 10,
         *       "seed": 2026,
         *       "servers": 10,
         *       "simulation_time": 2000,
         *       "warmup_time": 100
         *     }
         */
        MMCSimulateRequest: {
            /**
             * Lambda
             * @description Taxa média de chegada (λ).
             */
            lambda: number;
            /**
             * Mu
             * @description Taxa média de serviço (μ).
             */
            mu: number;
            /**
             * Simulation Time
             * @description Tempo simulado por replicação.
             */
            simulation_time: number;
            /**
             * Replications
             * @description Número de replicações.
             * @default 10
             */
            replications: number;
            /**
             * Warmup Time
             * @description Período inicial descartado (transitório).
             * @default 0
             */
            warmup_time: number;
            /**
             * Seed
             * @description Semente aleatória. Se omitida, uma é sorteada e devolvida.
             */
            seed?: number | null;
            /**
             * Confidence Level
             * @description Nível do intervalo de confiança (0 a 1).
             * @default 0.95
             */
            confidence_level: number;
            /**
             * Servers
             * @description Número de servidores (c).
             */
            servers: number;
        };
        /** MetricComparisonOut */
        MetricComparisonOut: {
            /** Analytical */
            analytical: number;
            /** Simulated Mean */
            simulated_mean: number;
            /** Ci Low */
            ci_low: number | null;
            /** Ci High */
            ci_high: number | null;
            /** Absolute Error */
            absolute_error: number;
            /** Relative Error Pct */
            relative_error_pct: number | null;
            /** Within Ci */
            within_ci: boolean | null;
        };
        /** MetricSummaryOut */
        MetricSummaryOut: {
            /** Mean */
            mean: number;
            /** Std */
            std: number | null;
            /** Ci Low */
            ci_low: number | null;
            /** Ci High */
            ci_high: number | null;
            /** N */
            n: number;
        };
        /** QueueCalculateResponse */
        QueueCalculateResponse: {
            /** Model */
            model: string;
            /** Servers */
            servers: number;
            /** Capacity */
            capacity: number | null;
            /** Rho */
            rho: number;
            /** L */
            L: number;
            /** Lq */
            Lq: number;
            /** W */
            W: number;
            /** Wq */
            Wq: number;
            /** P0 */
            p0: number;
            /** Throughput */
            throughput: number;
            /** P Wait */
            p_wait: number;
            /** P Block */
            p_block: number;
        };
        /** QueueComparisonResponse */
        QueueComparisonResponse: {
            /** Model */
            model: string;
            /** Lambda */
            lambda: number;
            /** Mu */
            mu: number;
            /** Servers */
            servers: number;
            /** Capacity */
            capacity: number | null;
            /** Simulation Time */
            simulation_time: number;
            /** Warmup Time */
            warmup_time: number;
            /** Replications */
            replications: number;
            /** Seed */
            seed: number;
            /** Confidence Level */
            confidence_level: number;
            /** Metrics */
            metrics: {
                [key: string]: components["schemas"]["MetricComparisonOut"];
            };
            /** All Within Ci */
            all_within_ci: boolean | null;
            /** Max Relative Error Pct */
            max_relative_error_pct: number | null;
        };
        /** QueueReplicationOut */
        QueueReplicationOut: {
            /** Index */
            index: number;
            /** Rho */
            rho: number;
            /** L */
            L: number;
            /** Lq */
            Lq: number;
            /** W */
            W: number;
            /** Wq */
            Wq: number;
            /** P0 */
            p0: number;
            /** Throughput */
            throughput: number;
            /** P Wait */
            p_wait: number;
            /** P Block */
            p_block: number;
            /** Measured Customers */
            measured_customers: number;
            /** Observation Time */
            observation_time: number;
        };
        /** QueueSimulationResponse */
        QueueSimulationResponse: {
            /** Model */
            model: string;
            /** Lambda */
            lambda: number;
            /** Mu */
            mu: number;
            /** Servers */
            servers: number;
            /** Capacity */
            capacity: number | null;
            /** Simulation Time */
            simulation_time: number;
            /** Warmup Time */
            warmup_time: number;
            /** Replications */
            replications: number;
            /** Seed */
            seed: number;
            /** Confidence Level */
            confidence_level: number;
            /** Runs */
            runs: components["schemas"]["QueueReplicationOut"][];
            /** Summary */
            summary: {
                [key: string]: components["schemas"]["MetricSummaryOut"];
            };
        };
        /** ReplicationOut */
        ReplicationOut: {
            /** Index */
            index: number;
            /** Rho */
            rho: number;
            /** L */
            L: number;
            /** Lq */
            Lq: number;
            /** W */
            W: number;
            /** Wq */
            Wq: number;
            /** P0 */
            p0: number;
            /** Throughput */
            throughput: number;
            /** Measured Customers */
            measured_customers: number;
            /** Observation Time */
            observation_time: number;
        };
        /** SimulationResponse */
        SimulationResponse: {
            /**
             * Model
             * @default M/M/1
             */
            model: string;
            /** Lambda */
            lambda: number;
            /** Mu */
            mu: number;
            /** Simulation Time */
            simulation_time: number;
            /** Warmup Time */
            warmup_time: number;
            /** Replications */
            replications: number;
            /** Seed */
            seed: number;
            /** Confidence Level */
            confidence_level: number;
            /** Runs */
            runs: components["schemas"]["ReplicationOut"][];
            /** Summary */
            summary: {
                [key: string]: components["schemas"]["MetricSummaryOut"];
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    calculate_api_models_mm1_calculate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MM1CalculateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MM1CalculateResponse"];
                };
            };
            /** @description Parâmetros inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    simulate_api_models_mm1_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MM1SimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResponse"];
                };
            };
            /** @description Parâmetros inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    compare_api_models_mm1_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MM1CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResponse"];
                };
            };
            /** @description Parâmetros inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    calculate_api_models_mmc_calculate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MMCCalculateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueCalculateResponse"];
                };
            };
            /** @description Parâmetros inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    simulate_api_models_mmc_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MMCSimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueSimulationResponse"];
                };
            };
            /** @description Parâmetros inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    compare_api_models_mmc_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MMCSimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueComparisonResponse"];
                };
            };
            /** @description Parâmetros inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    calculate_api_models_mm1k_calculate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MM1KCalculateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueCalculateResponse"];
                };
            };
            /** @description Parâmetros inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    simulate_api_models_mm1k_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MM1KSimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueSimulationResponse"];
                };
            };
            /** @description Parâmetros inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    compare_api_models_mm1k_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MM1KSimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueComparisonResponse"];
                };
            };
            /** @description Parâmetros inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    calculate_api_models_mmck_calculate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MMCKCalculateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueCalculateResponse"];
                };
            };
            /** @description Parâmetros inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    simulate_api_models_mmck_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MMCKSimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueSimulationResponse"];
                };
            };
            /** @description Parâmetros inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    compare_api_models_mmck_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MMCKSimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueComparisonResponse"];
                };
            };
            /** @description Parâmetros inválidos */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
